// essa aula toda foi feita emcima de FUNCIONARIOS.
//1 EXCLUIR NODE_MODULES'
//2 ENTRAR EM PACKAGTE.JSON DE FUNCIONARIOS
//3 APAGAR INDEX.JS 'QUE NAO EXISTE MAIS POR TER APAGADO NODE_MODULES' E COLOCAR NO LUGAR FUNCIONARIOS.JS
//4 INSERIR SCRIPST => "start": "nodemon", esse nao estava nas dependencias, mas estava no global, entao foi buscar 
//5 INSERIR SCRIPT => "dev": "nodemon"
//6 QUANDO EXECUTAR O NODEMON, ELE VAI PROCURAR QUAL O ARQUIVO PRINCIPAL, OU SEJA FUNCIONARIOS.JS, SE NAO ACHAR, VAI PRO GLOBAL PQ TENHO ELE INSTALADO
//7 DENTRO DA PASTA FUNCIONARIOS, RECRIAR O NODE_MODULES NO TERMINAL.  'npm i' Ele recria todas as dependencias
//8 DENTRO DE NODE_MODULES ESTARÃO TODAS AS DEPENDENCIAS, JA QUE TENHO OS SCRIPTS DEFINIDOS,  BASTA EXECUTAR 'npm start'
//9 APOS O NPM START, TODA APLICAÇAO DE FUNCIONARIOS RODOU, QUANDO COMENTAVA RESTARTAVA, QUANDO MUDAVA SINAL DE > PARA < RESTARTAVA
//10 'npm start' 'npm test' SAO COMANDOS PADRAO DO NODE, POREM RODA COM 'npm start' ou 'npm test'
//11  'npm test' ele mostra a msg de teste &&  exit + cod. cod 1 ou != 0 aconteceu algum erro, cod 0 = sucesso 
// 12 COMO DEV ou PODERIA SER BLABLABLA , E SETEI ELE PARA RODAR NODEMON, NÃO E PADRAO DO NODE, PARA RODAR PRECISA  'npm run dev'
// 13 OLHAR NA DOCUMENTAÇAO DO NPM, TEM RESTART STOP START TEST
